Repository NoBrainCp/nobrain-frontend, pull requests merged in 2023-03, with the labels that each got.

#39 Feature/main UI
  .idea/inspectionProfiles/Project_Default.xml
  src/assets/images/favicon.ico
  src/components/Book.vue
  src/components/CategoryBar.vue
  src/components/Head.vue
  src/components/Side.vue
  src/components/TagBar.vue
  src/views/Main.vue
Labels: feat, refactor

#42 Feature/confirm dialog
  src/components/CategoryBar.vue
  src/components/dialog/ConfirmDialog.vue
  src/components/main/Header.vue
  src/router/index.js
  src/views/Main.vue
  src/views/Main2.vue
  src/views/MainView.vue
Labels: feat

#43 feat: 북마크 및 카테고리 수정/삭제 연결
  src/components/Book.vue
  src/components/CategoryBar.vue
  src/components/Head.vue
  src/components/Side.vue
  src/components/dialog/ConfirmDialog.vue
  src/components/form/BookmarkDialog.vue
  src/components/form/CategoryDialog.vue
  src/components/main/Bookmark.vue
  src/components/main/CategorySubBar.vue
Labels: feat

#44 feat: 전역 변수 설정
  src/store/store.js
Labels: feat

#45 feat: web storage 데이터 저장 기능 구현
  package.json
  src/components/Head.vue
  src/components/Side.vue
  src/components/form/BookmarkDialog.vue
  src/components/form/CategoryDialog.vue
  src/main.js
  src/store/index.js
  src/store/module.js
  src/views/sign/SignIn.vue
  src/views/sign/SignUp.vue
  yarn.lock
Labels: feat

#48 [#47] style: change sign code
  src/views/change/ChangePassword.vue
  src/views/sign/SignIn.vue
  src/views/sign/SignUp.vue
Labels: clean-up

#50 [#49] feat: Connected Basic Component
  src/router/index.js
  src/views/UserProfile.vue
Labels: feat

#51 [#49] feat:Implemented user information page
  src/components/Profile.vue
  src/views/UserProfile.vue
Labels: feat

#52 [#49] feat: 유저정보 페이지 메인 페이지 연결기능 구현
  src/components/Head.vue
  src/views/MainView.vue
Labels: feat

#55 Feature/api modularization
  .env
  src/api/index.js
  src/components/alert/Alert.vue
  src/store/index.js
  src/store/module.js
  src/store/module/signin.js
  src/views/sign/SignIn.vue
  src/views/sign/SignUp.vue
Labels: feat, refactor

#56 Feature/api modularization
  src/api/index.js
  src/api/user/userApi.js
  src/components/Head.vue
  src/components/Side.vue
  src/router/index.js
  src/store/index.js
  src/store/module/signin.js
  src/utils/cookies.js
  src/views/sign/SignIn.vue
  src/views/sign/SignUp.vue
Labels: feat

#57 [#47]: style: 로그인 페이지 이동 코드 개선
  src/views/sign/SignIn.vue
Labels: clean-up

#58 Feature/api modularization
  src/api/bookmark/bookmarkApi.js
  src/api/category/categoryApi.js
  src/api/index.js
  src/api/user/userApi.js
  src/components/Book.vue
  src/components/CategoryBar.vue
  src/components/Head.vue
  src/components/Profile.vue
  src/components/Side.vue
  src/components/form/CategoryDialog.vue
  src/main.js
  src/router/index.js
  src/store/bookmark/bookmark.js
  src/views/MainView.vue
  src/views/bookmarkCategory.vue
  src/views/sign/SignIn.vue
Labels: feat

#61 Feature/side vue api
  src/api/category/categoryApi.js
  src/api/common/interceptors.js
  src/api/user/userApi.js
  src/components/Bookmark.vue
  src/components/CategoryBar.vue
  src/components/Header.vue
  src/components/Profile.vue
  src/components/Side.vue
  src/components/SideBar.vue
  src/components/form/BookmarkDialog.vue
  src/components/form/CategoryDialog.vue
  src/components/main/Bookmark.vue
  src/components/main/CategorySubBar.vue
  src/components/main/Header.vue
  src/components/main/SideBar.vue
  src/router/index.js
  src/store/category/category.js
  src/store/index.js
  src/views/Main2.vue
  src/views/MainView.vue
  src/views/bookmarkCategory.vue
Labels: feat, refactor, clean-up

#62 Feature/bookmark api
  src/api/bookmark/bookmarkApi.js
  src/components/Bookmark.vue
  src/components/CategoryBar.vue
  src/components/SideBar.vue
  src/components/dialog/BookmarkDialog.vue
  src/components/dialog/CategoryDialog.vue
  src/components/form/UpdateCategoryForm.vue
  src/store/bookmark/bookmark.js
  src/store/category/category.js
  src/views/sign/SignIn.vue
Labels: help wanted

#63 [#54] feat: 카테고리 추가 API 호출 개선
  src/components/SideBar.vue
Labels: feat

#64 [#60] feat: 북마크 추가 API 연결
  src/components/Bookmark.vue
  src/components/SideBar.vue
  src/components/dialog/BookmarkDialog.vue
  src/components/dialog/CategoryDialog.vue
Labels: feat

#65 [Feature/bookmark api] 북마크 수정, 삭제, 변경 API 연결 ** BACK-END 수정 필수**
  src/api/bookmark/bookmarkApi.js
  src/components/Bookmark.vue
  src/components/SideBar.vue
  src/components/dialog/BookmarkDialog.vue
  src/components/dialog/ConfirmDialog.vue
  src/store/bookmark/bookmark.js
Labels: feat, refactor

#67 feature/tag api
  src/api/index.js
  src/api/tag/tagApi.js
  src/components/Bookmark.vue
  src/components/SideBar.vue
  src/components/dialog/BookmarkDialog.vue
Labels: feat

#70 [Category api] category API 연결
  src/api/category/categoryApi.js
  src/api/tag/tagApi.js
  src/components/dialog/BookmarkDialog.vue
  src/components/main/Bookmark.vue
  src/components/main/CategoryBar.vue
  src/components/main/Header.vue
  src/components/main/Profile.vue
  src/components/main/SideBar.vue
  src/components/main/TagBar.vue
  src/views/MainView.vue
Labels: feat, clean-up

#71 Feature/tag api
  src/api/tag/tagApi.js
  src/components/main/Bookmark.vue
  src/components/main/SideBar.vue
  src/components/main/TagBar.vue
Labels: feat, clean-up

#74 [#72] feat: 전체 북마크 검색 API 연결
  src/api/bookmark/bookmarkApi.js
  src/components/main/Bookmark.vue
  src/components/main/Header.vue
Labels: feat

#75 [#73] feat: 팔로우 API 연결
  src/api/follow/followApi.js
  src/api/index.js
  src/components/main/Bookmark.vue
  src/components/main/SideBar.vue
Labels: feat

#76 feature/search
  src/api/follow/followApi.js
  src/components/main/Bookmark.vue
  src/components/main/CategoryBar.vue
  src/components/main/Header.vue
  src/components/main/SideBar.vue
Labels: feat, refactor

#77 feature/profile
  src/api/user/userApi.js
  src/components/main/Header.vue
  src/components/main/Profile.vue
  src/components/main/SideBar.vue
  src/store/user/user.js
  src/utils/cookies.js
Labels: feat, refactor, clean-up

#80 feature/profile
  src/api/user/userApi.js
  src/components/main/Profile.vue
  src/views/change/ChangePassword.vue
Labels: feat

#82 Feature/follow list UI
  src/api/common/interceptors.js
  src/components/dialog/CategoryDialog.vue
  src/components/icons/IconDocumentation.vue
  src/components/icons/IconPlusBox.vue
  src/components/icons/IconStar.vue
  src/components/main/Bookmark.vue
  src/components/main/CategoryBar.vue
  src/components/main/Follow.vue
  src/components/main/Header.vue
  src/components/main/SideBar.vue
  src/components/main/UserCard.vue
  src/store/follow/follow.js
  src/views/MainView.vue
Labels: feat

#85 fix/ dialog
  src/api/bookmark/bookmarkApi.js
  src/components/dialog/BookmarkDialog.vue
  src/components/dialog/CategoryDialog.vue
  src/components/main/Bookmark.vue
  src/components/main/CategoryBar.vue
  src/components/main/SideBar.vue
Labels: feat, fix

#86 [Feature/follow card api] 변경된 follow api 연결 및 변경 감지로직 추가
  src/api/common/interceptors.js
  src/api/follow/followApi.js
  src/components/main/SideBar.vue
  src/components/main/UserCard.vue
Labels: feat, refactor

#87 feature/logout
  src/components/main/Header.vue
  src/components/main/Profile.vue
  src/utils/cookies.js
Labels: feat, fix

#88 [Refactor/follow card api] follow store 변경 감지 로직 수정 및 user card 조건 추가
  src/components/main/SideBar.vue
  src/components/main/UserCard.vue
Labels: feat, refactor

#90 [#89] feat: Starred Category UI 구현 및 Starred Bookmark 조회 API 연결
  src/api/bookmark/bookmarkApi.js
  src/components/main/Bookmark.vue
  src/components/main/SideBar.vue
Labels: feat

#91 [#89] feat: Starred Bookmark count API 연결
  src/api/bookmark/bookmarkApi.js
  src/components/main/SideBar.vue
Labels: feat

#94 feature/category-api
  src/api/category/categoryApi.js
  src/components/main/CategoryBar.vue
  src/components/main/Profile.vue
  src/components/main/SideBar.vue
  src/utils/cookies.js
Labels: feat

#95 feature/starred category
  src/components/main/Bookmark.vue
  src/components/main/CategoryBar.vue
  src/components/main/SideBar.vue
  src/store/favorites/favorites.js
Labels: feat, fix

#97 feature/starred category
  src/api/category/categoryApi.js
  src/components/dialog/BookmarkDialog.vue
  src/components/dialog/ConfirmDialog.vue
  src/components/main/Bookmark.vue
  src/components/main/CategoryBar.vue
  src/components/main/Header.vue
  src/components/main/Profile.vue
  src/components/main/SideBar.vue
Labels: feat, fix

#102 [#59] refactor: 유저 프로필 이미지 변경 및 조회 API 개선
  src/api/user/userApi.js
  src/components/main/Profile.vue
Labels: refactor

#104 feature/interseptors
  src/api/common/interceptors.js
  src/assets/images/not-found-search.png
  src/components/dialog/BookmarkDialog.vue
  src/components/dialog/CategoryDialog.vue
  src/components/main/CategoryBar.vue
  src/components/main/Header.vue
  src/components/main/NoSearch.vue
  src/components/main/SideBar.vue
  src/views/MainView.vue
Labels: feat, refactor, fix

#106 feature/composition Api
  src/api/auth/authApi.js
  src/api/common/common.js
  src/api/common/interceptors.js
  src/api/user/userApi.js
  src/assets/images/error-background.png
  src/assets/images/error-logo.png
  src/assets/images/error-page.png
  src/assets/images/error-text.png
  src/components/alert/Alert.vue
  src/components/certifiedcard/FindByCertifiedCard.vue
  src/components/dialog/SignUpDialog.vue
  src/components/error/ErrorPage.vue
  src/utils/cookies.js
  src/views/NotFound.vue
  src/views/change/ChangePassword.vue
  src/views/find/FIndByPassword.vue
  src/views/find/FindById.vue
  src/views/find/ForgetPassword.vue
  src/views/sign/SignIn.vue
  src/views/sign/SignUp.vue
Labels: feat, refactor, fix

#107 Refactor/composition api
  src/components/dialog/AuthDialog.vue
  src/components/dialog/BookmarkDialog.vue
  src/components/dialog/CategoryDialog.vue
  src/components/dialog/ConfirmDialog.vue
  src/components/dialog/ImageFileDialog.vue
  src/components/main/Bookmark.vue
  src/components/main/CategoryBar.vue
  src/components/main/Follow.vue
  src/components/main/Header.vue
  src/components/main/NoSearch.vue
  src/components/main/Profile.vue
  src/components/main/SideBar.vue
  src/components/main/TagBar.vue
  src/components/main/UserCard.vue
  src/utils/cookies.js
  src/views/MainView.vue
  src/views/sign/SignIn.vue
Labels: refactor

#109 Refactor/composition api
  src/components/dialog/BookmarkDialog.vue
  src/components/dialog/CategoryDialog.vue
  src/components/dialog/ConfirmDialog.vue
  src/components/main/Bookmark.vue
  src/components/main/CategoryBar.vue
  src/components/main/Header.vue
  src/components/main/Profile.vue
  src/components/main/SideBar.vue
  src/router/index.js
Labels: refactor, fix

#110 Refactor/composition api
  src/components/main/Bookmark.vue
  src/components/main/SideBar.vue
  src/components/main/UserCard.vue
  src/views/MainView.vue
Labels: fix
