Repository NoBrainCp/nobrain-frontend, pull requests merged in 2023-04, with the labels that each got.

#114 feature/start page
  src/assets/images/google-logo.png
  src/assets/images/kakao-logo.png
  src/assets/images/light-on.png
  src/assets/images/naver-logo.png
  src/assets/images/start-page-favorite.png
  src/assets/images/start-page-follow.png
  src/assets/images/start-page-header.jpg
  src/assets/images/start-page-img.png
  src/assets/images/start-page-public.png
  src/assets/images/start-page-search.png
  src/assets/images/start-page-tag.png
  src/components/start/Body.vue
  src/components/start/Footer.vue
  src/components/start/Function.vue
  src/components/start/Header.vue
  src/main.js
  src/router/index.js
  src/views/StartPage.vue
Labels: feat, refactor

#115 Feature/start page
  src/components/main/Header.vue
  src/components/start/Body.vue
  src/components/start/Function.vue
  src/components/start/Header.vue
Labels: feat, refactor, clean-up

#117 [Feature/main UI] Main UI 개선
  src/components/start/Body.vue
  src/components/start/Function.vue
  src/components/start/Header.vue
  src/views/StartPage.vue
Labels: style

#119 Feature/start page
  src/assets/images/background.jpg
  src/components/certifiedcard/FindByCertifiedCard.vue
  src/components/find/ChangePassword.vue
  src/components/find/FindByInfo.vue
  src/components/find/ForgetPassword.vue
  src/components/main/Bookmark.vue
  src/components/start/Body.vue
  src/router/index.js
  src/views/Find.vue
  src/views/find/FIndByPassword.vue
  src/views/find/FindById.vue
  src/views/find/ForgetPassword.vue
  src/views/sign/SignIn.vue
Labels: feat, refactor, clean-up

#120 [#113] code-clean: 컴포넌트 clean-up
  src/components/find/ForgetPassword.vue
  src/components/start/Body.vue
  src/views/Find.vue
Labels: clean-up

#121 Feature/start page
  src/components/certifiedcard/FindByCertifiedCard.vue
  src/components/start/Body.vue
  src/components/start/Footer.vue
  src/components/start/Header.vue
  src/router/index.js
  src/views/Find.vue
  src/views/StartPage.vue
Labels: refactor

#122 feature/start page
  src/App.vue
  src/assets/fonts/doveFont.ttf
  src/assets/fonts/neoFont.ttf
  src/assets/images/sign-up-background.jpg
  src/components/certifiedcard/FindByCertifiedCard.vue
  src/components/start/Header.vue
  src/views/Find.vue
  src/views/sign/SignUp.vue
Labels: feat, refactor, clean-up

#123 Feature/start page
  src/App.vue
  src/assets/fonts/doveFont.ttf
  src/components/login/Body.vue
  src/components/login/Footer.vue
  src/components/login/Function.vue
  src/components/login/Header.vue
  src/main.js
  src/router/index.js
  src/store/index.js
  src/views/FindView.vue
  src/views/LoginView.vue
  src/views/NotFoundView.vue
  src/views/SignUpView.vue
  src/views/sign/SignIn.vue
Labels: refactor, clean-up

#124 feature/start page
  src/assets/images/login-page-favorite.png
  src/assets/images/login-page-follow.png
  src/assets/images/login-page-header.jpg
  src/assets/images/login-page-img.png
  src/assets/images/login-page-public.png
  src/assets/images/login-page-search.png
  src/assets/images/login-page-tag.png
  src/components/login/Body.vue
  src/components/login/Function.vue
  src/views/FindView.vue
  src/views/SignUpView.vue
  yarn.lock
Labels: refactor, clean-up

#128 [Feature/oauth2 social login] Oauth2 Social Login 기능 구현
  src/api/oauth/OAuthApi.js
  src/assets/images/github-logo.png
  src/components/login/Body.vue
  src/components/login/OauthSignIn.vue
  src/router/index.js
  src/store/index.js
Labels: feat

#131 Feature/error handling
  src/components/certifiedcard/FindByCertifiedCard.vue
  src/components/dialog/BookmarkDialog.vue
  src/components/find/ChangePassword.vue
  src/components/main/Bookmark.vue
  src/components/main/CategoryBar.vue
  src/components/main/Profile.vue
  src/components/main/SideBar.vue
  src/router/index.js
  src/views/NotFoundView.vue
Labels: refactor

#133 [#132] feat: local storiage util class 구현
  src/components/login/Body.vue
  src/components/login/OauthSignIn.vue
  src/utils/storage.js
Labels: feat

#134 Feature/local storage
  src/api/common/common.js
  src/api/common/interceptors.js
  src/components/dialog/BookmarkDialog.vue
  src/components/login/OauthSignIn.vue
  src/components/main/Bookmark.vue
  src/components/main/CategoryBar.vue
  src/components/main/Header.vue
  src/components/main/Profile.vue
  src/components/main/SideBar.vue
  src/components/main/UserCard.vue
  src/router/index.js
  src/store/index.js
  src/store/module/signin.js
  src/utils/cookies.js
  src/views/NotFoundView.vue
Labels: feat

#136 [#135] feat: follow count 동적 변경 처리
  src/components/main/SideBar.vue
  src/components/main/UserCard.vue
  src/store/follow/follow.js
Labels: refactor
