Repository NoBrainCp/nobrain-frontend, pull requests merged in 2023-02, with the labels that each got.

#12 Category sub bar
  package.json
  src/components/Bookmark.vue
  src/components/CategorySubBar.vue
  src/components/CreateBookmarkForm.vue
  src/components/SideBar.vue
  src/main.js
  yarn.lock
Labels: feat, refactor

#13 Feature/forgetpassword
  src/components/ForgetId.vue
  src/components/ForgetPassword.vue
Labels: feat

#14 Feature/forgetpassword
  src/components/ForgetId.vue
Labels: bug, feat

#19 Feature/forgetpassword
  src/components/certifiedcard/FindByCertifiedCard.vue
  src/components/dialog/SignUpDialog.vue
  src/views/find/FindById.vue
  src/views/sign/SignUp.vue
Labels: feat, refactor

#20 Refactor/main UI
  package.json
  src/assets/imges/logo.png
  src/assets/imges/logo.svg
  src/assets/imges/logo_transparent.png
  src/components/main/Bookmark.vue
  src/components/main/CategorySubBar.vue
  src/components/main/Header.vue
  yarn.lock
Labels: feat

#23 feat: 비밀번호 변경 view
  src/components/certifiedcard/FindByCertifiedCard.vue
  src/router/index.js
  src/views/change/ChangePassword.vue
Labels: feat

#26 Feature/send authentication phonenumber
  src/components/certifiedcard/FindByCertifiedCard.vue
  src/views/sign/SignIn.vue
Labels: feat

#27 feat: implemented login function
  src/views/sign/SignIn.vue
  src/views/sign/SignUp.vue
Labels: feat

#30 [#29] refactor: URL 수정
  src/views/sign/SignUp.vue
Labels: refactor

#31 feat: signup design
  src/views/sign/SignUp.vue
Labels: feat

#34 [#33] feat: 메인 페이지 이동 및 북마크 검증 규칙
  src/components/certifiedcard/FindByCertifiedCard.vue
  src/components/form/CreateBookmarkForm.vue
  src/components/main/Header.vue
  src/views/find/ForgetPassword.vue
  src/views/sign/SignUp.vue
Labels: feat

#37 Feature/main UI
  src/assets/images/nobrain-no-image.png
  src/components/Book.vue
  src/components/CategoryBar.vue
  src/components/Head.vue
  src/components/Side.vue
  src/router/index.js
  src/views/Main.vue
Labels: feat, refactor
